import Link from 'next/link'

export const metadata = {
  title: 'Terms & Conditions — EduDraftAI',
  description: 'Terms and Conditions for using EduDraftAI by Yuktra AI.',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-bg">
      <header className="bg-navy px-6 py-4 flex items-center justify-between">
        <Link href="/" className="text-white font-bold text-lg tracking-tight">
          EduDraft<span className="text-teal">AI</span>
        </Link>
        <Link href="/login" className="text-sm text-white/70 hover:text-white transition-colors">
          Login →
        </Link>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-12">
        <h1 className="text-3xl font-bold text-navy mb-2">Terms &amp; Conditions</h1>
        <p className="text-muted text-sm mb-8">Last updated: April 20, 2026</p>

        <div className="space-y-8 text-text text-sm leading-relaxed">

          <section>
            <h2 className="text-lg font-bold text-navy mb-2">1. Acceptance of Terms</h2>
            <p>
              By accessing or using EduDraftAI (&quot;the Service&quot;), operated by <strong>Yuktra AI</strong>
              (sole proprietorship), you agree to be bound by these Terms &amp; Conditions. If you do not
              agree, do not use the Service. The Service is available at{' '}
              <a href="https://edudraftai.com" className="text-teal hover:underline">edudraftai.com</a>.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-navy mb-2">2. Description of Service</h2>
            <p>
              EduDraftAI is a B2B SaaS platform that provides AI-powered content generation tools for
              diploma college lecturers. Users can generate lesson notes, MCQ banks, question banks,
              and internal test plans aligned with their institution&apos;s approved syllabus. Access is
              granted on a per-college subscription basis managed by college administrators.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-navy mb-2">3. Eligibility &amp; Account Access</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>You must be a verified employee (lecturer or administrator) of a registered college institution.</li>
              <li>Access is granted by your college administrator and is non-transferable.</li>
              <li>You are responsible for maintaining the security of your login credentials.</li>
              <li>Yuktra AI reserves the right to suspend accounts that violate these terms.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-navy mb-2">4. Credit System &amp; Payments</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>The Service operates on a prepaid credit model. Each AI content generation costs 1 credit.</li>
              <li>Credits are purchased by college administrators via Razorpay (UPI, cards, net banking).</li>
              <li>Credits are non-transferable between colleges and do not expire as long as the account is active.</li>
              <li>All prices are in Indian Rupees (INR) and inclusive of applicable taxes.</li>
              <li>Payments are processed securely by Razorpay. Yuktra AI does not store payment credentials.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-navy mb-2">5. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li>Use the Service for any unlawful, harmful, or abusive purpose.</li>
              <li>Attempt to reverse-engineer, scrape, or automate requests to the platform.</li>
              <li>Share your account credentials with unauthorized persons.</li>
              <li>Submit offensive, plagiarized, or copyrighted content as syllabus input.</li>
              <li>Use AI-generated content as a direct substitute for professional academic judgment — always review outputs before use.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-navy mb-2">6. AI-Generated Content Disclaimer</h2>
            <p>
              Content generated by EduDraftAI is produced by large language models (OpenAI GPT-4o and
              Anthropic Claude) and is intended as a drafting aid only. Yuktra AI does not guarantee
              the accuracy, completeness, or suitability of generated content for any specific purpose.
              Users are solely responsible for reviewing, editing, and validating AI outputs before
              institutional use.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-navy mb-2">7. Intellectual Property</h2>
            <p>
              The EduDraftAI platform, branding, and underlying software are the property of Yuktra AI.
              AI-generated content created using your syllabus and prompts belongs to you and your
              institution. By uploading syllabus documents, you grant Yuktra AI a limited licence to
              process them for the purpose of providing the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-navy mb-2">8. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Yuktra AI shall not be liable for any indirect,
              incidental, or consequential damages arising from your use of the Service. Our total
              liability shall not exceed the amount paid by you in the 3 months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-navy mb-2">9. Modifications to Service</h2>
            <p>
              Yuktra AI reserves the right to modify, suspend, or discontinue any part of the Service
              at any time with reasonable notice. Credit balances will not be forfeited due to service
              modifications — unused credits will be refunded in such an event.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-navy mb-2">10. Governing Law</h2>
            <p>
              These Terms are governed by the laws of India. Any disputes shall be subject to the
              exclusive jurisdiction of the courts in Odisha, India.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-navy mb-2">11. Contact</h2>
            <p>
              For questions about these Terms:<br />
              <strong>Yuktra AI</strong><br />
              Email: <a href="mailto:info@yuktraai.com" className="text-teal hover:underline">info@yuktraai.com</a><br />
              Website: <a href="https://edudraftai.com" className="text-teal hover:underline">edudraftai.com</a>
            </p>
          </section>

        </div>
      </main>

      <footer className="border-t border-border mt-12 py-6 px-6 text-center text-xs text-muted">
        <div className="flex justify-center gap-6 mb-2">
          <Link href="/privacy-policy" className="hover:text-text transition-colors">Privacy Policy</Link>
          <Link href="/refund-policy" className="hover:text-text transition-colors">Refund Policy</Link>
          <Link href="/contact" className="hover:text-text transition-colors">Contact Us</Link>
        </div>
        © {new Date().getFullYear()} Yuktra AI. All rights reserved.
      </footer>
    </div>
  )
}
